/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Application.Main;
import Services.IServiceBan;
import Services.ServiceBan;
import ViewModels.BanView;
import java.awt.Color;
import java.util.List;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucif
 */
public class ChuyenBan extends javax.swing.JDialog {

    int a;
    int getID;
    IServiceBan svsBan = new ServiceBan();
    /**
     * Creates new form NewJDialog
     */
    private Main banhang;

    public ChuyenBan(java.awt.Frame parent, boolean modal, int kieu, int id) {
        super(parent, modal);
        a = kieu;
        getID = id;
        initComponents();
        banhang = (Main) parent;
        if(a==1){
            loadTableBan(svsBan.findBanGop(id));
        }else{
        loadTableBan(svsBan.findByStatus(kieu));
    }
    }

    void loadTableBan(List<BanView> bv) {
        DefaultTableModel tbl = (DefaultTableModel) tbl_chuyenBan.getModel();
        tbl.setRowCount(0);
        for (BanView x : bv) {
            tbl.addRow(new Object[]{
                x.getMaBan(),
                x.getTrangThai() == 1 ? "Hoạt động" : "Trống"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_chuyenBan = new javax.swing.JTable();
        btn_xacNhan = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(209, 171, 134));

        tbl_chuyenBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã bàn", "Trạng thái", "Mã hóa đơn"
            }
        ));
        tbl_chuyenBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_chuyenBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_chuyenBan);

        btn_xacNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_xacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        btn_xacNhan.setText("Xác nhận");
        btn_xacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacNhanActionPerformed(evt);
            }
        });

        btn_huy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("CHUYỂN BÀN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btn_xacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_chuyenBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_chuyenBanMouseClicked
        int index = tbl_chuyenBan.getSelectedRow();// TODO add your handling code here:
    }//GEN-LAST:event_tbl_chuyenBanMouseClicked

    private void btn_xacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacNhanActionPerformed
        if (a == 0) {
            int index = tbl_chuyenBan.getSelectedRow();
            int idBan = Integer.parseInt(tbl_chuyenBan.getValueAt(index, 0).toString().substring(1));
            svsBan.chuyenBan(getID, idBan);
        } else {
            int index = tbl_chuyenBan.getSelectedRow();
            int idBan = Integer.parseInt(tbl_chuyenBan.getValueAt(index, 0).toString().substring(1));
            svsBan.gopBan(getID, idBan);
        }
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xacNhanActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        BanHang bh = (BanHang) Main.currentPanel;
        bh.demoLoad();
    }//GEN-LAST:event_btn_huyActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_xacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_chuyenBan;
    // End of variables declaration//GEN-END:variables
}
