/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import DomainModel.Ban;
import Services.ServiceBan;
import Utilities.GetID;
import ViewModels.BanView;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.ImplBangBan;

/**
 *
 * @author Ngọc Hùng
 */
public class JPanelBan extends javax.swing.JPanel {

    /**
     * Creates new form JPanelNhanVien
     */
    DefaultTableModel _DefaultTableModel;
    ServiceBan _ServiceBan = new ServiceBan();
    ImplBangBan _daoBan;
    GetID _getid; 

    public JPanelBan() {
        initComponents();
        _DefaultTableModel = new DefaultTableModel();
        _ServiceBan = new ServiceBan();
        _daoBan = new ImplBangBan();
        _getid = new GetID();
        txt_MaBan.setEnabled(false);
        trangThai();
        loadTable(_ServiceBan.getlst());
        
    }

    void trangThai() {
        cbx_TrangThai.removeAllItems();
        cbx_TrangThai.addItem("Trống");
        cbx_TrangThai.addItem("Có khách");
        cbx_TrangThai.addItem("Không sử dụng");
    }

    void loadTable(List<Ban> lst) {
        _DefaultTableModel = (DefaultTableModel) tbl_Ban.getModel();
        if (lst.isEmpty()) {
            _DefaultTableModel.setRowCount(0);
            return;
        }
        
        _DefaultTableModel.setRowCount(0);
        for (Ban x : lst) {
            _DefaultTableModel.addRow(new Object[]{
                x.getMaBan(), x.getTrangThai() == 0 ? "Trống" : x.getTrangThai() == 1 ? "Có khách" : "Không sử dụng", x.getSoGhe()
            });
        }
    }

    BanView getGUI(int style) {
        int ma = _daoBan.findAll().get(_daoBan.findAll().size()-1).getID_Ban();
        if (style == 1) {
            return new BanView(_getid.getIDMax("B", ma), cbx_TrangThai.getSelectedItem() == "Trống" ? 0 : cbx_TrangThai.getSelectedItem() == "Trống" ? 1 : 2, Integer.parseInt(txt_SoGhe.getText()));
        }
        return new BanView(_ServiceBan.getlst().get(tbl_Ban.getSelectedRow()).getID_Ban(), txt_MaBan.getText(), cbx_TrangThai.getSelectedItem() == "Trống" ? 0 : cbx_TrangThai.getSelectedItem() == "Trống" ? 1 : 2, Integer.parseInt(txt_SoGhe.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaBan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbx_TrangThai = new javax.swing.JComboBox<>();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ban = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_SoGhe = new javax.swing.JTextField();

        setBackground(new java.awt.Color(209, 171, 134));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bàn");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã bàn :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trạng thái :");

        cbx_TrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Them.setBackground(new java.awt.Color(204, 255, 204));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus.png"))); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(153, 255, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loading.png"))); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        tbl_Ban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã bàn", "Trạng thái", "Số ghế"
            }
        ));
        tbl_Ban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Ban);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Số ghế");

        txt_SoGhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoGheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(0, 843, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_MaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(txt_SoGhe)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbx_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Sua)
                    .addComponent(jLabel4)
                    .addComponent(txt_SoGhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_BanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BanMouseClicked
        // TODO add your handling code here:
        int index = tbl_Ban.getSelectedRow();
        txt_MaBan.setText(tbl_Ban.getModel().getValueAt(index, 0).toString());
        cbx_TrangThai.setSelectedItem(tbl_Ban.getModel().getValueAt(index, 1).toString());
        txt_SoGhe.setText(tbl_Ban.getModel().getValueAt(index, 2).toString());
    }//GEN-LAST:event_tbl_BanMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog(this, "Xác nhận!");
        if (choose == 0) {
            _ServiceBan.create(getGUI(1));
            loadTable(_ServiceBan.getlst());
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            return;
        }
        JOptionPane.showMessageDialog(this, "Thêm thất bại!");

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        if (tbl_Ban.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn bàn");
            return;
        }

        int choose = JOptionPane.showConfirmDialog(this, "Xác nhận!");
        if (choose == 0) {
            _ServiceBan.update(getGUI(0));
            loadTable(_ServiceBan.getlst());
            JOptionPane.showMessageDialog(this, "Sửa thành công!");
            return;
        }
        JOptionPane.showMessageDialog(this, "Sửa thất bại!");
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void txt_SoGheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoGheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoGheActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JComboBox<String> cbx_TrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tbl_Ban;
    private javax.swing.JTextField txt_MaBan;
    private javax.swing.JTextField txt_SoGhe;
    // End of variables declaration//GEN-END:variables
}
